### ISSUE TITLE
Error in npm install with puppeteer package

### ISSUE THREAD

**Issue by ydorLorenzo** [peppelongo96/UnicalDown#3]
While executing `npm install` the process brakes with an error. The package **puppeteer** cannot be installed.

```
693 verbose stack Error: puppeteer@5.2.1 install: `node install.js`
693 verbose stack Exit status 1
693 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
693 verbose stack     at EventEmitter.emit (events.js:223:5)
693 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
693 verbose stack     at ChildProcess.emit (events.js:223:5)
693 verbose stack     at maybeClose (internal/child_process.js:1021:16)
693 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
694 verbose pkgid puppeteer@5.2.1
695 verbose cwd C:\Projects\UnicalDown
696 verbose Windows_NT 10.0.18362
697 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
698 verbose node v12.14.1
699 verbose npm  v6.13.4
700 error code ELIFECYCLE
701 error errno 1
702 error puppeteer@5.2.1 install: `node install.js`
702 error Exit status 1
703 error Failed at the puppeteer@5.2.1 install script.
703 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by peppelongo96** [comment]
Hi,

Thanks for the issue. Please follow the last [v1.7.4](https://github.com/peppelongo96/UnicalDown#v174) version. All should be fixed :)
